import Menu from "@/components/Menu";
import Logo from "@/components/assets/Logo";
import ChannelMenu from "@/components/client/ChannelMenu";
import { isAuthenticatedOrRedirected } from "@/services/helpers/isAuthenticatedOrRedirected";

export const metadata = {
  title: "Wellnify | Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //todo: Make next-auth take over this part. This is just a fill-in to simulate a user logged in.
  await isAuthenticatedOrRedirected();

  return (
    <div className="grid grid-cols-dashboard p-3 relative z-10">
      {/* //*Nav menu on the left that stays static across all pages */}
      <div>
        <Logo />
        <Menu />
      </div>
      <div className="px-3 max-h-screen">{children}</div>
      {/* This is the Page/:path* rendering */}
      <div className="px-3">
        <ChannelMenu />
      </div>
    </div>
  );
}
